apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc16-odoo
  labels:
    app: uc16-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uc16-odoo
  template:
    metadata:
      labels:
        app: uc16-odoo
    spec:
      nodeName: k8s-worker02
      containers:
        - name: odoo
          image: 192.168.1.233/uc16_odoo:latest
          command: ["odoo", "--dev", "xml"]
          ports:
            - containerPort: 8069
          # Add resource limits
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          envFrom:
            - secretRef:
                name: odoo-env
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
            - name: extra-addons
              mountPath: /mnt/extra-addons
            - name: odoo-conf
              mountPath: /etc/odoo
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: new-odoo-pvc
        - name: extra-addons
          hostPath:
            path: /mnt/extra-addons
            type: DirectoryOrCreate
        - name: odoo-conf
          hostPath:
            path: /mnt/sara-odoo-conf
            type: DirectoryOrCreate
