apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc16-odoo
  labels:
    app: uc16-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uc16-odoo
  template:
    metadata:
      labels:
        app: uc16-odoo
    spec:
      # NodeSelector to force pod onto worker01
      #nodeSelector:
        #kubernetes.io/hostname: k8s-worker02
      containers:
<<<<<<< HEAD
        - name: odoo
          image: 192.168.1.233:9955/uc16_odoo:latest
          command: ["odoo", "--dev", "xml"]
          ports:
            - containerPort: 8069
          envFrom:
            - secretRef:
                name: odoo-env
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
            - name: extra-addons
              mountPath: /mnt/extra-addons
      volumes:
=======
      - name: odoo
        image: 192.168.1.233:5000/uc16_odoo:latest
        command: ["odoo", "--dev", "xml"]
        ports:
        - containerPort: 8069
        envFrom:
        - secretRef:
            name: odoo-env
        volumeMounts:
>>>>>>> d1b7712 (Initial commit)
        - name: odoo-data
          mountPath: /var/lib/odoo
        - name: extra-addons
          mountPath: /mnt/extra-addons
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo-pvc
      - name: extra-addons
        hostPath:
          path: /mnt/extra-addons
          type: DirectoryOrCreate

