apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-odoo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#  volumeName: new-odoo-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-odoo-pv
spec:
  #storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/odooData"
    type: DirectoryOrCreate
